parameters:
    database_host:      mariadb
    database_name:      chitanka
    database_user:      root
    database_password:  ~
    database_driver:    pdo_mysql
    database_port:      ~

    secret: ThisTokenIsNotSoSecretChangeIt